language: python
python:
  - "3.3"
  - "3.4"
sudo: false
branches:
    only:
        - master
install:
    pip install .
    pip install coverage coveralls nose
script: 
    ./test.sh
after_success:
    coveralls
